### PR TITLE
opam file for why3 proof, switch to GitHub Actions CI, fix Dune build

### PR DESCRIPTION
**Pull request by palmskog**
We can no longer use Travis, so we switch to GitHub Actions for CI. To eventually enable testing the Why3 proof in CI, I created a separate opam package.

### CODE REVIEW

**Comment by palmskog** [comment]
@thery any reservations, or can I merge this?

**Comment by thery** [comment]
yes you can merge.
Ps : you have been smarter than I am. I could not make it why3 replay work without the library being installed.

**Comment by palmskog** [comment]
In fact I did not solve the issue with replay only working with the library installed (I suspect one has to pass some configuration option to `why3` which then passes it to `coqc`). However, with a separate opam package for the replay, the assumption is anyway that all Coq files are installed.

**Comment by thery** [comment]
Let's see what the why3 expect think : [518](https://gitlab.inria.fr/why3/why3/-/issues/518)

**Comment by thery** [comment]
There is a work around but maybe your solution is better [518](https://gitlab.inria.fr/why3/why3/-/issues/518)

**Comment by palmskog** [comment]
How about we document both options - running with installed Bertrand proof and local Bertrand proof? I still think the installed option is to be preferred in continuous integration, though, to avoid having to fiddle with Why3 configuration files inside the Docker container.

**Comment by thery** [comment]
Let's wait they close the issue ;-)

**Pull request merged**
